test_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  setup_macos_script: |
    mkdir -p ~/Library/Audio/Plug-Ins/Vamp
    cd ci
    cp pyin-arm64.dylib pyin.n3 pyin.cat ~/Library/Audio/Plug-Ins/Vamp
    
  test_macos_arm64_python310_script: |
    brew install python@3.10
    
    python3.10 -m pip install vamphost
    python3.10 test1.py

  test_macos_arm64_python311_script: |
    brew install python@3.11
  
    python3.11 -m pip install vamphost
    python3.11 test1.py
