[build-system]
requires = [
    "setuptools>=77",
    "numpy>=2.0",
]
build-backend = "setuptools.build_meta"


[project]
name = "vamphost"
version = "1.4.0"
description = "Use Vamp plugins for audio feature analysis."
readme = "README.rst"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE.txt"]
authors = [
    { name = "Chris Cannam", email = "cannam@all-day-breakfast.com" },
    { name = "George Fazekas" },
]
maintainers = [
    { name = "Eduardo Moguillansky", email = "eduardo.moguillansky@gmail.com" },
]
dependencies = [
    "numpy",
]
urls = { Homepage = "https://code.soundsoftware.ac.uk/projects/vampy-host" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Multimedia :: Sound/Audio :: Analysis",
]


[tool.setuptools.packages.find]
include = ["vamp*"]


[tool.cibuildwheel]
build = "cp310-* cp311-* cp312-* cp313-*"
skip = "pp* *686* *-musllinux_*"
