name: test

on: [push, pull_request]

jobs:
  test:
    name: test on ${{ matrix.os }}, python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        python-version: [ "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: prepare tests in linux x86_64
        if: runner.os == 'linux' && runner.arch == 'X64'
        run: |
          mkdir -p ~/vamp
          cd testci
          cp linux-x86_64/pyin.so pyin.n3 pyin.cat ~/vamp

      - name: prepare tests in mac x86_64
        if: runner.os == 'macos' && runner.arch == 'X64'
        run: |
          mkdir -p ~/Library/Audio/Plug-Ins/Vamp
          cd testci
          cp macos-x86_64/pyin.dylib pyin.n3 pyin.cat ~/Library/Audio/Plug-Ins/Vamp

      - name: prepare tests in mac arm64
        if: runner.os == 'macos' && runner.arch == 'ARM64'
        run: |
          mkdir -p ~/Library/Audio/Plug-Ins/Vamp
          cd testci
          cp macos-arm64/pyin.dylib pyin.n3 pyin.cat ~/Library/Audio/Plug-Ins/Vamp


      - name: prepare tests win
        if: runner.os == 'windows'
        run: |
          mkdir "C:/Program Files/Vamp Plugins" -ea 0
          cd testci
          Copy-Item win-x86_64/pyin.dll -Destination "C:\Program Files\Vamp Plugins"
          Copy-Item pyin.n3  -Destination "C:\Program Files\Vamp Plugins"
          Copy-Item pyin.cat -Destination "C:\Program Files\Vamp Plugins"

      - name: run tests
        run: |
          cd testci
          
          pip install -U vamphost
          pip install -r requirements.txt
          python test1.py
          python test2.py snd/tuning-fork--A4.flac

